# Generated by Django 4.2.7 on 2025-08-27 06:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the mechanic shop', max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinate', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinate', max_digits=9)),
                ('address', models.TextField(help_text='Full address of the shop')),
                ('contact', models.CharField(help_text='Phone number', max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Rating from 0.0 to 5.0', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('working_hours', models.TextField(help_text='Working hours (e.g., Mon-Fri: 8AM-6PM, Sat: 9AM-4PM)')),
                ('image', models.ImageField(blank=True, help_text='Shop image', null=True, upload_to='mechanic_images/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the shop is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mechanic Shop',
                'verbose_name_plural': 'Mechanic Shops',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text="User's phone number", max_length=20)),
                ('address', models.TextField(blank=True, help_text="User's address")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(help_text="Type of search (e.g., 'distance', 'rating')", max_length=50)),
                ('user_location', models.CharField(help_text="User's location coordinates", max_length=100)),
                ('radius', models.IntegerField(help_text='Search radius in kilometers')),
                ('results_count', models.IntegerField(help_text='Number of results returned')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search Query',
                'verbose_name_plural': 'Search Queries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('search', 'Search for mechanics'), ('view', 'View mechanic details'), ('call', 'Call mechanic'), ('filter', 'Apply filters'), ('login', 'User login'), ('logout', 'User logout'), ('admin_action', 'Admin action')], help_text='Type of action performed', max_length=20)),
                ('details', models.TextField(blank=True, help_text='Additional details about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="User's IP address", null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the action occurred')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (null for anonymous users)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
